### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#17]
## Value statement - a requirement, not a solution
As a **event participant** 
I need **a search function** 
so that **I can find events faster** 

## Description (Text, Scribble, Wireframe, Design)

![W9 - SearchbarEvent](https://user-images.githubusercontent.com/67911386/91632966-ef9bc580-e9e4-11ea-9aea-5384567aca4a.png)

## Acceptance criteria
- [x] there will be an autocorrect after typing 3 letters , the autocorrect words are all event names
- [x] by pressing enter, the autocorrect word will used to listen the events up, which includes the searched word

## Tasks
- [x] create a searchbar
- [x] integrate the searchbar at the event main page, like the wire frame shows it
- [x] update storybook
- [ ] write tests
- [x] update styling

## Size
large

**Comment by jennydely** [comment]
QA Test:  Searchbar
[App](https://event-planner.jennydely.vercel.app/l)

**Comment by karstenlenz** [comment]
QA results (tested on MacOS/Firefox + Android/Chrome):

- if your search doesn't find any items, you just get an empty list. It would be better to get a message like "We couldn't find any events for searchterm 'lorem ipsum' ", so the user doesn't think it's a bug.
- An empty search gets you an empty list. I think it would be better to require at least one character to submit the search.
- It is unclear how to return to the list with all entries after searching. The only ways I found was to reload the page or change the category once and then back to "all".
- it is unclear what you can search for. I tried searching for a location like "Spanien" and didn't get any result.
- if you have selected a category such as "metal" and search, you can find events from other categories. However,  the category will still be displayed as "metal". 
- on the search result page, the sorting options don't work.

**Comment by jennydely** [comment]
updated the issues in my new pull request
