### ISSUE TITLE
Guestpage

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#58]
## Value statement - a requirement, not a solution
As a **guest** 
I need **possibility to see the eventlist without to login** 
so that **I can check out the app and the events without account** 

## Description (Text, Scribble, Wireframe, Design)
![Guest_login](https://user-images.githubusercontent.com/67911386/99999301-3f114800-2dc0-11eb-82ba-531bba6ec720.png)

All guests have access to the eventlist,the can filter and search them, but they cant interact with the events.

## Acceptance criteria
- [ ] the whole public event will be shown
- [ ] the filters and search option works
- [ ] there are not action and buttons avaiable like add, edit, bookmark etc.
- [ ] there should be an login possibility shown on the page menue

## Tasks
- [ ] create the component "guestpage"
- [ ] integrate the guestpage into the eventview app
- [ ] do tests

## Size
medium
