### ISSUE TITLE
Main Page with Login

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#59]
## Value statement - a requirement, not a solution
As a **user of eventview** 
I need **an mainpage** 
so that **I can choose if I want to use the app as guest or login as user** 

## Description (Text, Scribble, Wireframe, Design)
![Mainpage](https://user-images.githubusercontent.com/67911386/100259348-67c44980-2f48-11eb-9bf7-98077e29114d.png)

There should be an mainpage, where users can login with their google account or guest can use eventview as guest without login.

## Acceptance criteria
- [x] there is an login with google function
- [x] there is an go farward as guest option
- [x] it's not possible to get to the eventview list without chose one of these options

## Tasks
- [x] create an mainpage with login function
- [x] integrate the page into react router
- [ ] create tests

## Size
(small)
