### ISSUE TITLE
Bookmark Function for Events

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#60]
## Value statement - a requirement, not a solution
As a **user** 
I need **an bookmark button for the events** 
so that **I can bookmark events and find them in my privat bookmark list** 

## Description (Text, Scribble, Wireframe, Design)

![UserLogin](https://user-images.githubusercontent.com/67911386/100004377-b39bb500-2dc7-11eb-97b6-59170d4b8183.png)

There will be an bookmark button at each event.

## Acceptance criteria
- [ ] with click on the bookmark button, will the event be bookmarked and shown in the favourite list

## Tasks
- [ ] create an Bookmark Button
- [ ] create an privat, personal Bookmark list
- [ ] write tests

## Size
(medium)
