### ISSUE TITLE
Favourite Event List

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#61]
## Value statement - a requirement, not a solution
As a **user** 
I need **a private favourite list** 
so that **have an overview of all my favorite events** 

## Description (Text, Scribble, Wireframe, Design)
![User favoritenliste](https://user-images.githubusercontent.com/67911386/100005734-b7c8d200-2dc9-11eb-97b1-8068b7392888.png)

There will be a favourite list, where all bookmarked events from the public eventlist will be shown. Events can directly deleted here from the favourite list or used as template for own events.

## Acceptance criteria
- [ ] the favourite list can be chosen via dropdown menue
- [ ] all bookmarked events will be shown in this list
- [ ] if the event will be deleted here, it will just be deleted in the favourite list and not in the public list
- [ ] bookmarked events can be edited, they will be used as template then and will be saved as new event

## Tasks
- [ ] create favourite list
- [ ] create favoruit list functionallity
- [ ] create tests
- [ ] update storybook

## Size
(large)
