### ISSUE TITLE
Add Event to Google calendar

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#62]
## Value statement - a requirement, not a solution
As a **user or guest** 
I need **a function to add the event to my own google calendar** 
so that **I have the event as reminder in my private calender** 

## Description (Text, Scribble, Wireframe, Design)
![EventDetails_AddGoogleCalendar](https://user-images.githubusercontent.com/67911386/100257137-e23f9a00-2f45-11eb-9189-73d3b3749a7a.png)

With an click at the button, the chosen event will added to my privat google calendar

## Acceptance criteria
- [ ] with click at the button, a new window willopen and ask, if the user will add this event to the privat google calendar
- [ ] the function is avaiable for guests and users
- [ ] the google entry will use all infos from the event for the calendar entry

## Tasks
- [ ] integrate the button
- [ ] integrate the functionality to add the event to the google calendar

## Size
(small)
