### ISSUE TITLE
Choose Visibility of the Event

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#63]
## Value statement - a requirement, not a solution
As a **user** 
I need **a function to set the visibility of the event** 
so that **I can create owwn private events or public events** 

## Description (Text, Scribble, Wireframe, Design)

![CreateEvent_visibility](https://user-images.githubusercontent.com/67911386/100258018-d86a6680-2f46-11eb-8b04-3c442cfb3cac.png)

![EditEvent_visibility](https://user-images.githubusercontent.com/67911386/100258002-d56f7600-2f46-11eb-8607-36e15ac8e73b.png)

With the dropdown menu, the events can be set private or public

## Acceptance criteria
- [x] the default visibility of the events is private
- [ ]  by switching private and public in the dropdown menu, the event must directly switch into the other list

## Tasks
- [x] integrate the drop down menu 
- [x] set the visibility of the events
- [ ] update storybook

## Size
( medium)
