### ISSUE TITLE
Choose Visibility of the Packlists

### ISSUE THREAD

**Issue by jennydely** [jennydely/EventView#64]
## Value statement - a requirement, not a solution
As a **user** 
I need **a function to set the visibility of the packlists** 
so that **I can create owwn private Packlists or public packlists** 

## Description (Text, Scribble, Wireframe, Design)
![Packlist_visibility](https://user-images.githubusercontent.com/67911386/100259693-c8538680-2f48-11eb-8ff0-7eb512afd3e5.png)

With the dropdown menu, the packlist can be set private or public

## Acceptance criteria
- [x] the default visibility of the packlist is private
- [ ]  by switching private and public in the dropdown menu, the packlist must directly switch into the other list

## Tasks
- [x] integrate the drop down menu 
- [x] set the visibility of the packlists
- [ ] update storybook

## Size
( medium)
